apiVersion: apps/v1
kind: Deployment
metadata:
  name: nife-nginx
  labels:
    app: nife-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nife-nginx
  template:
    metadata:
      labels:
        app: nife-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: nife-nginx-service
spec:
  selector:
    app: nife-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

